### ISSUE TITLE
Integrate BBB call

### ISSUE THREAD

**Issue by nylser** [naklar-io/naklar.io#45]
Start bbb-call and embed via iframe

**Comment by rasaford** [comment]
getting the following error when calling `joinMeeting()`

{"Response Payload":{"EDITOR_CONFIG":{"text":"AttributeError at /roulette/meeting/join/37173060-4b47-49d7-bfc1-483b789fbf2a/\n'NoneType' object has no attribute 'text'\n\nRequest Method: POST\nRequest URL: https://dev.api.naklar.io/roulette/meeting/join/37173060-4b47-49d7-bfc1-483b789fbf2a/\nDjango Version: 3.0.5\nPython Executable: /usr/local/bin/uwsgi\nPython Version: 3.6.9\nPython Path: ['.', '', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/web/naklar.io/venv/lib/python3.6/site-packages']\nServer time: Mi, 15 Apr 2020 17:55:35 +0200\nInstalled Applications:\n['django.contrib.admin',\n 'django.contrib.auth',\n 'django.contrib.contenttypes',\n 'django.contrib.sessions',\n 'django.contrib.messages',\n 'django.contrib.staticfiles',\n 'channels',\n 'drf_yasg',\n 'corsheaders',\n 'drf_base64',\n 'account',\n 'call',\n 'roulette',\n 'landing',\n 'rest_framework',\n 'knox']\nInstalled Middleware:\n['django.middleware.security.SecurityMiddleware',\n 'django.contrib.sessions.middleware.SessionMiddleware',\n 'corsheaders.middleware.CorsMiddleware',\n 'django.middleware.common.CommonMiddleware',\n 'django.middleware.csrf.CsrfViewMiddleware',\n 'django.contrib.auth.middleware.AuthenticationMiddleware',\n 'django.contrib.messages.middleware.MessageMiddleware',\n 'django.middleware.clickjacking.XFrameOptionsMiddleware']\n\n\nTraceback (most recent call last):\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/django/core/handlers/exception.py\", line 34, in inner\n    response = get_response(request)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/django/core/handlers/base.py\", line 115, in _get_response\n    response = self.process_exception_by_middleware(e, request)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/django/core/handlers/base.py\", line 113, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py\", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/django/views/generic/base.py\", line 71, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/rest_framework/views.py\", line 505, in dispatch\n    response = self.handle_exception(exc)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/rest_framework/views.py\", line 465, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/rest_framework/views.py\", line 476, in raise_uncaught_exception\n    raise exc\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/rest_framework/views.py\", line 502, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/web/naklar.io/venv/lib/python3.6/site-packages/rest_framework/decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n  File \"./roulette/views.py\", line 189, in join_meeting\n    url = match.meeting.create_join_link(user, moderator=True)\n  File \"./roulette/models.py\", line 260, in create_join_link\n    self.create_meeting()\n  File \"./roulette/models.py\", line 228, in create_meeting\n    self.attendee_pw = root.find(\"attendeePW\").text\n\nException Type: AttributeError at /roulette/meeting/join/37173060-4b47-49d7-bfc1-483b789fbf2a/\nException Value: 'NoneType' object has no attribute 'text'\nRequest information:\nUSER: tutor@naklar.io <d26e4f55-39cc-4b3e-9392-f56df3f3d082>\n\nGET: No GET data\n\nPOST: No POST data\n\nFILES: No FILES data\n\nCOOKIES: No cookie data\n\nMETA:\nCONTENT_LENGTH = '0'\nCONTENT_TYPE = ''\nDOCUMENT_ROOT = '/usr/share/nginx/html'\nHTTPS = 'on'\nHTTP_ACCEPT = 'application/json, text/plain, */*'\nHTTP_ACCEPT_ENCODING = 'gzip, deflate'\nHTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.5'\nHTTP_AUTHORIZATION = 'Token 9d1cc68a0534352228e31aa9df15faf0038874e419f42c708117d5bcb0c35d47'\nHTTP_CACHE_CONTROL = 'no-cache'\nHTTP_CONNECTION = 'close'\nHTTP_CONTENT_LENGTH = '0'\nHTTP_HOST = 'dev.api.naklar.io'\nHTTP_ORIGIN = 'http://localhost:4200'\nHTTP_PRAGMA = 'no-cache'\nHTTP_REFERER = 'http://localhost:4200/roulette/tutor'\nHTTP_USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0'\nPATH_INFO = '/roulette/meeting/join/37173060-4b47-49d7-bfc1-483b789fbf2a/'\nQUERY_STRING = ''\nREMOTE_ADDR = '141.84.69.84'\nREMOTE_PORT = '59504'\nREQUEST_METHOD = 'POST'\nREQUEST_SCHEME = 'https'\nREQUEST_URI = '/roulette/meeting/join/37173060-4b47-49d7-bfc1-483b789fbf2a/'\nSCRIPT_NAME = ''\nSERVER_NAME = 'dev.api.naklar.io'\nSERVER_PORT = '443'\nSERVER_PROTOCOL = 'HTTP/1.1'\nuwsgi.node = b'ubuntu-django'\nuwsgi.version = b'2.0.18'\nwsgi.errors = <_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>\nwsgi.file_wrapper = ''\nwsgi.input = <uwsgi._Input object at 0x7f4c25601de0>\nwsgi.multiprocess = True\nwsgi.multithread = False\nwsgi.run_once = False\nwsgi.url_scheme = 'https'\nwsgi.version = '(1, 0)'\n\nSettings:\nUsing settings module naklario.settings\nABSOLUTE_URL_OVERRIDES = {}\nADMINS = []\nALLOWED_HOSTS = ['bbb.goodgrade.de', 'localhost', '127.0.0.1', 'api.naklar.io', 'dev.api.naklar.io']\nAPPEND_SLASH = True\nASGI_APPLICATION = 'naklario.routing.application'\nAUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']\nAUTH_PASSWORD_VALIDATORS = '********************'\nAUTH_USER_MODEL = 'account.CustomUser'\nBASE_DIR = '/home/web/naklar.io/backend/naklar-io'\nBBB_SHARED = 'iFsEVFiFzXVJkgYHWEEBdf6PIcu39Az0gLn522K2UI'\nBBB_URL = 'https://bbb.goodgrade.de'\nCACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}\nCACHE_MIDDLEWARE_ALIAS = 'default'\nCACHE_MIDDLEWARE_KEY_PREFIX = '********************'\nCACHE_MIDDLEWARE_SECONDS = 600\nCORS_ORIGIN_WHITELIST = ['https://dev.naklar.io']\nCSRF_COOKIE_AGE = 31449600\nCSRF_COOKIE_DOMAIN = None\nCSRF_COOKIE_HTTPONLY = False\nCSRF_COOKIE_NAME = 'csrftoken'\nCSRF_COOKIE_PATH = '/'\nCSRF_COOKIE_SAMESITE = 'Lax'\nCSRF_COOKIE_SECURE = False\nCSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'\nCSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'\nCSRF_TRUSTED_ORIGINS = []\nCSRF_USE_SESSIONS = False\nDATABASES = {'default': {'ENGINE': 'django.db.backends.mysql', 'NAME': 'dev_database', 'USER': 'dev_database', 'PASSWORD': '********************', 'HOST': 'localhost', 'PORT': '3306', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}}\nDATABASE_ROUTERS = []\nDATA_UPLOAD_MAX_MEMORY_SIZE = 10485760\nDATA_UPLOAD_MAX_NUMBER_FIELDS = 1000\nDATETIME_FORMAT = 'N j, Y, P'\nDATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y']\nDATE_FORMAT = 'N j, Y'\nDATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y']\nDEBUG = True\nDEBUG_PROPAGATE_EXCEPTIONS = False\nDECIMAL_SEPARATOR = '.'\nDEFAULT_CHARSET = 'utf-8'\nDEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'\nDEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'\nDEFAULT_FROM_EMAIL = 'webmaster@localhost'\nDEFAULT_INDEX_TABLESPACE = ''\nDEFAULT_TABLESPACE = ''\nDISALLOWED_USER_AGENTS = []\nEMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'\nEMAIL_HOST = 'mail.gandi.net'\nEMAIL_HOST_PASSWORD = '********************'\nEMAIL_HOST_USER = 'noreply@naklar.io'\nEMAIL_PORT = 587\nEMAIL_SSL_CERTFILE = None\nEMAIL_SSL_KEYFILE = '********************'\nEMAIL_SUBJECT_PREFIX = '[Django] '\nEMAIL_TIMEOUT = None\nEMAIL_USE_LOCALTIME = False\nEMAIL_USE_SSL = False\nEMAIL_USE_TLS = True\nFILE_CHARSET = 'utf-8'\nFILE_UPLOAD_DIRECTORY_PERMISSIONS = None\nFILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']\nFILE_UPLOAD_MAX_MEMORY_SIZE = 2621440\nFILE_UPLOAD_PERMISSIONS = 420\nFILE_UPLOAD_TEMP_DIR = None\nFIRST_DAY_OF_WEEK = 0\nFIXTURE_DIRS = []\nFORCE_SCRIPT_NAME = None\nFORMAT_MODULE_PATH = None\nFORM_RENDERER = 'django.forms.renderers.DjangoTemplates'\nHOST = 'https://dev.naklar.io'\nIGNORABLE_404_URLS = []\nINSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'channels', 'drf_yasg', 'corsheaders', 'drf_base64', 'account', 'call', 'roulette', 'landing', 'rest_framework', 'knox']\nINTERNAL_IPS = []\nLANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')]\nLANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur']\nLANGUAGE_CODE = 'de-de'\nLANGUAGE_COOKIE_AGE = None\nLANGUAGE_COOKIE_DOMAIN = None\nLANGUAGE_COOKIE_HTTPONLY = False\nLANGUAGE_COOKIE_NAME = 'django_language'\nLANGUAGE_COOKIE_PATH = '/'\nLANGUAGE_COOKIE_SAMESITE = None\nLANGUAGE_COOKIE_SECURE = False\nLOCALE_PATHS = []\nLOGGING = {}\nLOGGING_CONFIG = 'logging.config.dictConfig'\nLOGIN_REDIRECT_URL = '/accounts/profile/'\nLOGIN_URL = '/accounts/login/'\nLOGOUT_REDIRECT_URL = None\nMANAGERS = []\nMEDIA_ROOT = ''\nMEDIA_URL = '/media/'\nMESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'\nMIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware']\nMIGRATION_MODULES = {}\nMONTH_DAY_FORMAT = 'F j'\nNUMBER_GROUPING = 0\nPASSWORD_HASHERS = '********************'\nPASSWORD_RESET_TIMEOUT_DAYS = '********************'\nPREPEND_WWW = False\nREST_FRAMEWORK = {'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'], 'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer'], 'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.BasicAuthentication', 'knox.auth.TokenAuthentication']}\nROOT_URLCONF = 'naklario.urls'\nSECRET_KEY = '********************'\nSECURE_BROWSER_XSS_FILTER = False\nSECURE_CONTENT_TYPE_NOSNIFF = True\nSECURE_HSTS_INCLUDE_SUBDOMAINS = False\nSECURE_HSTS_PRELOAD = False\nSECURE_HSTS_SECONDS = 0\nSECURE_PROXY_SSL_HEADER = None\nSECURE_REDIRECT_EXEMPT = []\nSECURE_REFERRER_POLICY = None\nSECURE_SSL_HOST = None\nSECURE_SSL_REDIRECT = False\nSERVER_EMAIL = 'root@localhost'\nSESSION_CACHE_ALIAS = 'default'\nSESSION_COOKIE_AGE = 1209600\nSESSION_COOKIE_DOMAIN = None\nSESSION_COOKIE_HTTPONLY = True\nSESSION_COOKIE_NAME = 'sessionid'\nSESSION_COOKIE_PATH = '/'\nSESSION_COOKIE_SAMESITE = 'Lax'\nSESSION_COOKIE_SECURE = False\nSESSION_ENGINE = 'django.contrib.sessions.backends.db'\nSESSION_EXPIRE_AT_BROWSER_CLOSE = False\nSESSION_FILE_PATH = None\nSESSION_SAVE_EVERY_REQUEST = False\nSESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'\nSETTINGS_MODULE = 'naklario.settings'\nSHORT_DATETIME_FORMAT = 'm/d/Y P'\nSHORT_DATE_FORMAT = 'm/d/Y'\nSIGNING_BACKEND = 'django.core.signing.TimestampSigner'\nSILENCED_SYSTEM_CHECKS = []\nSTATICFILES_DIRS = []\nSTATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder']\nSTATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'\nSTATIC_ROOT = '/home/web/naklar.io/backend/naklar-io/static/'\nSTATIC_URL = '/static/'\nSWAGGER_SETTINGS = {'SECURITY_DEFINITIONS': {'Token': '********************'}, 'SECURITY_REQUIREMENTS': [{'Token': []}], 'REFETCH_SCHEMA_WITH_AUTH': True, 'PERSIST_AUTH': True}\nTEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]\nTEST_NON_SERIALIZED_APPS = []\nTEST_RUNNER = 'django.test.runner.DiscoverRunner'\nTHOUSAND_SEPARATOR = ','\nTIME_FORMAT = 'P'\nTIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']\nTIME_ZONE = 'Europe/Berlin'\nUSE_I18N = True\nUSE_L10N = True\nUSE_THOUSAND_SEPARATOR = False\nUSE_TZ = True\nUSE_X_FORWARDED_HOST = False\nUSE_X_FORWARDED_PORT = False\nWSGI_APPLICATION = 'naklario.wsgi.application'\nX_FRAME_OPTIONS = 'DENY'\nYEAR_MONTH_FORMAT = 'F Y'\n\n\nYou're seeing this error because you have DEBUG = True in your\nDjango settings file. Change that to False, and Django will\ndisplay a standard page generated by the handler for this status code.\n\n","mode":"text/plain"}}}
